name: 'shipping_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'shipping_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  shipping_dbt_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
    core:
      +materialized: table

vars:
  # Add custom variables here
  telegram_schema: "raw"
  analytics_schema: "analytics" 