shipping_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', 5432) }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', '0581') }}"
      dbname: "{{ env_var('DB_NAME', 'shipping_data_warehouse') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_dev') }}"
      threads: 4
      keepalives_idle: 0
      search_path: "{{ env_var('DBT_SCHEMA', 'dbt_dev') }}"
    
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', 5432) }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'password') }}"
      dbname: "{{ env_var('DB_NAME', 'shipping_data_warehouse') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_prod') }}"
      threads: 4
      keepalives_idle: 0
      search_path: "{{ env_var('DBT_SCHEMA', 'dbt_prod') }}" 