telegram_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', '') }}"
      dbname: "{{ env_var('DB_NAME', 'telegram_data') }}"
      schema: "{{ env_var('DB_SCHEMA', 'analytics') }}"
      threads: 4
      keepalives_idle: 0
      search_path: analytics, raw
      connect_timeout: 10
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', '') }}"
      dbname: "{{ env_var('DB_NAME', 'telegram_data') }}"
      schema: "{{ env_var('DB_SCHEMA', 'analytics') }}"
      threads: 8
      keepalives_idle: 0
      search_path: analytics, raw
      connect_timeout: 10 